version: '3.4'

services:
  web:
    image: docdanio/petsta
    build: ./petsta
    command: gunicorn petsta.wsgi:application --bind 0.0.0.0:8000
    volumes:
    - ./staticfiles:/tmp/petsta/staticfiles
    ports:
    - 8000:8000
    env_file:
    - ./petsta/envs/.env
    depends_on:
    - postgres
  postgres:
    image: postgres
    restart: always
    ports:
    - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres-user
      POSTGRES_DB: pet_db
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
    - ./postgresql:/var/lib/postgresql/data
  nginx:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./staticfiles:/home/app/web/staticfiles
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/comf/:/etc/nginx/ssl/:ro
    depends_on:
      - web